export const API = {
  GET_PLAYLIST: 'API/GET_PLAYLIST',
  POST_VIDEO: 'API/POST_VIDEO',
  DELETE_VIDEO: 'API/DELETE_VIDEO',
};

export const APP = {
  SET_PLAYLIST: 'APP/SET_PLAYLIST',
  SET_ACTIVE_VIDEO: 'APP/SET_ACTIVE_VIDEO',
  REMOVE_VIDEO_FROM_PLAYLIST: 'APP/REMOVE_VIDEO_FROM_PLAYLIST',
  SET_ALERT: 'APP/SET_ALERT',
  REMOVE_ALERT: 'APP/REMOVE_ALERT',
};
